// Detecta se é tela mobile (usado para ajustes de tamanho)
const isMobile = () => typeof window !== 'undefined' && window.innerWidth < 640;

export const sharedStyles = {
  wrapper: {
    position: 'relative',
    width: '100%',
    overflow: 'hidden',
    padding: '20px 0 40px',
    touchAction: 'pan-y',
  },
  track: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    perspective: '1200px',
    perspectiveOrigin: '50% 50%',
    minHeight: '380px',
    position: 'relative',
  },
  btnBase: (disabled) => ({
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    border: '1px solid rgba(168,85,247,0.3)',
    background: 'rgba(168,85,247,0.08)',
    color: disabled ? 'rgba(168,85,247,0.25)' : 'rgba(216,180,254,0.9)',
    fontSize: '18px',
    cursor: disabled ? 'not-allowed' : 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background 0.2s, color 0.2s',
    backdropFilter: 'blur(4px)',
    WebkitTapHighlightColor: 'transparent',
    flexShrink: 0,
  }),
  controls: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '16px',
    marginTop: '16px',
    padding: '0 12px',
  },
  dots: {
    display: 'flex',
    gap: '5px',
    alignItems: 'center',
    flexWrap: 'wrap',
    maxWidth: '65%',
    justifyContent: 'center',
  },
  dot: (active) => ({
    width: active ? '16px' : '6px',
    height: '6px',
    borderRadius: '9999px',
    background: active ? 'linear-gradient(to right, #a855f7, #ec4899)' : 'rgba(168,85,247,0.3)',
    transition: 'all 0.35s ease',
    cursor: 'pointer',
    minWidth: '6px',
  }),
  hint: (isTouch) => ({
    textAlign: 'center',
    marginTop: '16px',
    fontSize: '11px',
    letterSpacing: '0.12em',
    color: 'rgba(216,180,254,0.45)',
    textTransform: 'uppercase',
    padding: '0 16px',
  }),
  modalOverlay: (isOpen) => ({
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 9999,
    backgroundColor: 'rgba(0,0,0,0.9)',
    backdropFilter: 'blur(8px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: isOpen ? 1 : 0,
    pointerEvents: isOpen ? 'auto' : 'none',
    transition: 'opacity 0.4s ease',
    padding: '16px',
  }),
  modalCloseBtn: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    background: 'rgba(255,255,255,0.15)',
    border: '1px solid rgba(255,255,255,0.2)',
    boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
    borderRadius: '50%',
    width: '44px',
    height: '44px',
    color: 'white',
    fontSize: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'background 0.2s',
    zIndex: 10000,
    WebkitTapHighlightColor: 'transparent',
  },
  isMobile,
};
